### ISSUE TITLE
theory question

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#20]
I am getting and incorrect anergy for the single difference determinant, and I am wondering if I am doing something wrong theoretically. Since this doesn't have to do with numerics, I thought I might ask. If you told me to get lost, I actually wont get offended lol
https://github.com/pkozlows/fci/blob/d11bc5aea4f752c58305b6974ad86ee335a95b5f/latex/one_difference/combined.pdf

**Comment by Walter-Feng** [comment]
As far as I read it is consistent to what I see from wiki, as long as you know that you are using chemistry notation (consistent with the dimension in the two electron integrals provided), instead of the physical one in wiki.  

As usual, check spin, check range of summation, check phase factor. These three were the major problems I met when writing Full CI.
